TickyTocky/TickyTocky

src/components/common/DropDownList/DropDownList.module.scss
- Related Issue #55 
- Closes #55  
필요없는 box-shadow 속성을 삭제하였습니다
=> [24-02-02 우준석] 필요없는 box-shadow 속성 삭제

src/components/layout/modal/Modal.module.scss, src/stores/useModalStore.js
1. CommonModal & IconModal 공통
- responsive(M) , width 100%, margin: 0 1.5rem 적용
2. CommonModal
- CommonModal flex gap 삭제, label에 padding-bottom 적용
3. useModalStore
- isThirdModalOpen state 및 open close 메서드 추가
Related Issue #64 #65 
Closes #64 #65
=> [24-02-02 허우림] CommonModal, IconModal responsive 적용 및 useModalStore state 추가

src/components/common/DropDownList/DropDownList.module.scss, src/components/common/DropDownList/index.jsx, src/components/common/KebabDropDown/index.jsx
- Related Issue #61 #75
- Closes #61 #75 
활성화된 케밥버튼을 다시 클릭 시 활성화가 풀립니다.(오류로인해서 트랜지션 제거)
=> [24-02-03 우준석] 케밥 드랍다운의 박스 쉐도우가 보이지 않는 문제, 케밥버튼은 다시 클릭시  active가 풀리지 않는 문제 해결

src/components/auth/login/AuthForm.jsx, src/components/auth/signup/AuthForm.jsx
- AuthForm의 Auth 메소드 import문 수정
- Related Issue #
- Closes #
=> [24-02-24 허우림] AuthForm의 Auth 메소드 import문 수정

src/components/common/button/Button.module.scss
버튼 의 텍스트 사이즈 20폰트가 필요해서 업데이트합니다.
- Related Issue #97 
- Closes #97 
=> [24-02-06 고성선] 버튼 font-size 20추가

src/components/common/TagField/TagField.module.scss
TagField width값 변경 100%로 변경
- Related Issue #98 
- Closes #98
=> [24-02-06 우준석] TagField width값 변경

src/components/common/Avatar/index.jsx
1. 필수가 아닌 props에 기본값을 넣었습니다.
2. profileName이 없으면 렌더링 되지 않도록 하였습니다.
3. isArrow가 true일 때만 테두리가 나올 수 있게 if문을 추가하였습니다.
=> [24-02-07 유미정] Avatar 테두리가 불필요한 부분에서도 필수로 나오는 현상 해결

src/api/auth.js, src/api/dashboards.js, src/components/dashboard/DashboardCard/index.jsx, src/components/dashboard/DashboardList/index.jsx, src/components/dashboard/modal/dashboard/CreateDashboard.jsx, src/components/layout/Nav/index.jsx, src/components/nav/LinkButton.jsx, src/constants/auth.js, src/hooks/useDashboardList.js, src/pages/mydashboard/index.jsx
1. auth.js logout 메서드 추가
2. dashboard.js getList 메서드에 pagination과 page size 고정
3. mydashboard 페이지 구현
4. createDashboard 모달 closemodal 함수 수정
5. Nav에서 dashboard list get하고, 로그아웃 로직 추가
6. Nav의 link button에 max length 추가
7. constants/auth.js title validation regex 삭제
=> [24-02-10 허우림] Nav 버튼 링크 연결, mydashboard page 구현 등

src/components/columns/Column/index.jsx, src/components/dashboard/modal/card/CreateCard.jsx, src/components/dashboard/modal/card/CreateCard.module.scss, src/components/layout/dashboard/Column/ColumnLayout.module.scss, src/components/layout/modal/Modal.module.scss
- 카드 수정하기 완료 후 자동으로 리렌더링 안 되는 이슈 해결
- 카드 생성하기 컴포넌트 porps 수정
- 컬럼 레이아웃 : overflow scroll 스타일 적용
- 아이콘 모달 : 최소 너비 수정(모바일 맞춤)
=> [24-02-10 김희수] Edit card 리렌더링 이슈 해결, 스크롤 디자인 적용

src/components/common/CardTags/index.jsx, src/components/common/DropDown/index.jsx, src/components/common/DropDownList/index.jsx, src/components/common/InvitationMembers/index.jsx, src/components/common/TagField/index.jsx, src/components/dashboard/DashboardList/index.jsx, src/components/dashboard/dashboardEdit/DashboardInvitations.jsx, src/components/dashboard/dashboardEdit/DashboardMembers.jsx, src/components/dashboard/dashboardEdit/DashboardTitle.jsx, src/components/dashboard/modal/card/DetailCard.jsx, src/components/invitations/InvitationPopUp/index.jsx
- key 값 형식 통일
- 모두 유일한 key값으로 변경
=> [24-02-11 허우림] Edit all key property to be unique

src/components/nav/NavButton.module.scss
- nav 링크 버튼 text color gray10으로 변경
=> [24-02-11 허우림] Fix nav link button text color

src/components/dashboard/DashboardList/DashboardList.module.scss, src/components/dashboard/dashboardEdit/DashboardTitle.module.scss, src/components/layout/Nav/index.jsx, src/components/nav/LinkButton.jsx, src/components/nav/ModalButton.jsx, src/components/nav/NavButton.module.scss
- nav에서 해당 대시보드 페이지에 있을 시 대시보드 이미지에 css 효과 주도록 수정
- DashboardTitle의 컬러 팔레트에 padding left 
- DashboardList 모바일 사이즈에서 overflow-y 추가
=> [24-02-11 허우림] Nav, DashboardTitle, DashboardList 버그 수정

src/components/HeaderButtons/HeaderButtons.module.scss, src/components/common/InvitationMembers/InvitationMembers.module.scss, src/components/common/InvitationMembers/index.jsx, src/components/layout/Header/BoardHeader.jsx, src/hooks/useDashboardFetchData.js
1. 초대 버튼은 대시보드 생성자만 보이도록 하였습니다.
2. 대시보드 이동시 초대 버튼 유무가 바로 변경되도록 하였습니다.
3. 모바일일 때 헤더에 있는 초대 팝업 위치를 변경하였습니다.
=> [24-02-11 유미정] 대시보드 생성자만 초대 가능, 모바일일 때 초대 팝업 위치 변경

src/components/dashboard/DashboardList/DashboardList.module.scss, src/components/dashboard/dashboardEdit/DashboardMembers.module.scss, src/hooks/useCreateDashboard.js
1. DashboardList에서 좌측 하단 페이지네이션 버튼 border 수정
2. DashboardMember에서 멤버 리스트 padding 추가
3. useCreateDashboard에서 createDashboard 모달이 오픈되자마자 default black 컬러 클릭되도록 수정
=> [24-02-11 허우림] DashboardList, DashboardMember, useCreateDashboard 버그 수정

src/components/account/Account.module.scss
1. Account 페이지 Desktop과 Tablet 크기일 때 스크롤 안되는 문제 해결하였습니다.
2. 페이지 하단에 padding 추가하였습니다.
=> [24-02-11 유미정] Account 페이지 스크롤 안되는 문제 해결

src/components/common/ProfileModal/ProfileModal.module.scss, src/components/common/ProfileModal/index.jsx, src/components/layout/Header/MyHeader.jsx, src/components/layout/Nav/Nav.module.scss, src/components/layout/Nav/index.jsx
헤더와 nav의 로그아웃 버튼에 확인 모달을 추가하였습니다
- Related Issue #143 
- Closes #143
=> [24-02-11 우준석] logout 버튼들에 모달 구현

src/components/common/ProfileModal/index.jsx, src/components/layout/Nav/index.jsx
로그아웃 모달의 버튼 텍스트가 시안과 다른 문제 해결
- Related Issue #156  
- Closes #156
=> [24-02-12 우준석] 로그아웃 모달의 버튼 텍스트가 시안과 다른 문제 해결

src/hooks/useCreateDashboard.js
=> [24-02-12 허우림] useCreateDashboard 변경

src/components/common/ImageField/ProfileImage.jsx
마이페이지 접속시 콘솔에 에러 발생하여 확인하니 src주소가 발급전에 랜더링을 하면서 생기는 콘솔 에러였습니다.
- Related Issue #160 
- Closes #160 
=> [24-02-12 고성선] mypage 이미지 src관련 에러 

src/components/landing/DetailedFeatures/LandingDetailedFeatures.module.scss, src/components/landing/DetailedFeatures/index.js, src/components/landing/FeaturesOverview/landingFeaturesOverview.module.scss, src/components/landing/Footer/index.js
- 카드 패딩조절
- 푸터 깃허브 아이콘 주소변경
- 푸터 년도 시간에 따라 변경되게 설정
=> [24-02-12 우준석] 랜딩 페이지 구현

src/components/common/ProfileModal/index.jsx
ref를 함수에 직접주는 것을 변경하여 문제해결
- Related Issue #166 
- Closes #166
=> [24-02-12 우준석] profilemodal 클릭시 오류 발생 해결

src/components/layout/Nav/Nav.module.scss
dev pull 되지 않은 상태에서 머지되어 Nav 로그아웃 버튼 패딩 롤백됨
=> [24-02-12 우준석] Nav 로그아웃 버튼 패딩값 변경

src/components/columns/Column/index.jsx, src/components/common/InvitationMembers/index.jsx, src/components/common/Spinner/Spinner.module.scss, src/components/common/Spinner/index.jsx, src/components/dashboard/dashboardEdit/DashboardInvitations.jsx, src/components/dashboard/dashboardEdit/DashboardTitle.jsx, src/components/dashboard/modal/card/CreateCard.jsx, src/components/dashboard/modal/card/DetailCard.jsx, src/components/invitations/InvitationPopUp/index.jsx, src/components/layout/Header/BoardHeader.jsx, src/components/layout/Layouts/MainLayout.jsx, src/components/layout/dashboard/Column/index.jsx
로딩화면 Spinner 추가 해줬습니다. 
- Related Issue #172
- Closes #172 
=> [24-02-13 고성선] 로딩 Spinner 추가 

README.md
=> [24-02-15] Update README.md

README.md
=> [24-02-15]Update README.md

src/components/common/ImageField/ImageField.module.scss, src/components/common/ImageField/index.jsx
- 이미지 선택 초기화 기능입니다.
- 초기화 버튼 클릭 시 확인 모달이 뜨고 Apply 클릭 시 적용됩니다.
- previewImage, selectedImage 초기화 
- 초기화 확인 모달
- 초기화 완료
=> [24-02-15 김희수] 이미지 초기화 기능 추가

README.md, package.json, src/components/columns/Column/index.jsx, src/components/common/InvitationMembers/index.jsx, src/components/common/Spinner/Spinner.module.scss, src/components/common/Spinner/index.jsx, src/components/dashboard/dashboardEdit/DashboardInvitations.jsx, src/components/dashboard/dashboardEdit/DashboardMembers.jsx, src/components/dashboard/dashboardEdit/DashboardTitle.jsx, src/components/dashboard/modal/card/CreateCard.jsx, src/components/dashboard/modal/card/DetailCard.jsx, src/components/invitations/InvitationPopUp/index.jsx, src/components/layout/Header/BoardHeader.jsx, src/components/layout/Layouts/MainLayout.jsx, src/components/layout/dashboard/Column/index.jsx, src/hooks/useAsync.js, src/pages/_app.js, src/stores/useLoadingStore.js, src/styles/variables/_colors.scss
기존에 Spinner가 버벅거리는 이유는 useAsync의 isLoading으로 Spinner를 생성했기 때문에 useAsync를 호출하는 횟수만큼
Spinner가 생성됨 그로인해 버벅이는것으로 보임 그래서 하나의 상태로 isLoading을 관리하기 위해 zustand로 전역적으로
isLoading을 관리하고 spinner또한 app에서 호출하여 사용하게 변경 npm install 바람
- Related Issue #180 
- Closes #180 
=> [24-02-17 고성선] Spinner 버벅거림 현상 useAsync의 isLoading을 useLoadingStore로 전역 상태관리

src/components/common/SuccessModal/SucessModal.module.scss, src/components/common/SuccessModal/index.jsx
- [] 리팩터링
시안과 다른 success Modal button 사이즈 변경
- Related Issue #208 
- Closes #208 
=> [24-02-18 고성선] SuccessModal 닫는 버튼 사이즈 변경 
